# Implement LSH from scratch

In this assignment, you will implement LSH from scratch and predict the labels of the test data. You will then verify the correctness of the your implementation using a "grader" function/cell (provided by us) which will match your implmentation.

The grader fucntion would help you validate the correctness of your code. 

Please submit the final Colab notebook in the classroom ONLY after you have verified your code using the grader function/cell.


**NOTE: DO NOT change the "grader" functions or code snippets written by us.Please add your code in the suggested locations.**

Ethics Code:
1. You are welcome to read up online resources to implement the code. 
2. You can also discuss with your classmates on the implmentation over Slack.
3. But, the code you write and submit should be yours ONLY. Your code will be compared against other stduents' code and online code snippets to check for plagiarism. If your code is found to be plagiarised, you will be awarded zero-marks for all assignments, which have a 10% weightage in the final marks for this course.

## Reading the data from csv file

In [1]:
# Loading data from csv file
import pandas as pd
import pandas as pd
import os
os.chdir("D:\\AI and ML\\Dataset") # Set your directory 
df = pd.read_csv('lsh_assignment_data.csv') # load the data
df

           category                                               text
0              tech  tv future in the hands of viewers with home th...
1          business  worldcom boss  left books alone  former worldc...
2             sport  tigers wary of farrell  gamble  leicester say ...
3             sport  yeading face newcastle in fa cup premiership s...
4     entertainment  ocean s twelve raids box office ocean s twelve...
5          politics  howard hits back at mongrel jibe michael howar...
6          politics  blair prepares to name poll date tony blair is...
7             sport  henman hopes ended in dubai third seed tim hen...
8             sport  wilkinson fit to face edinburgh england captai...
9     entertainment  last star wars  not for children  the sixth an...
10    entertainment  berlin cheers for anti-nazi film a german movi...
11         business  virgin blue shares plummet 20% shares in austr...
12         business  crude oil prices back above $50 cold weather a...
13         politics  hague  given up  his pm ambition former conser...
14            sport  moya emotional after davis cup win carlos moya...
15         business  s korean credit card firm rescued south korea ...
16         politics  howard backs stem cell research michael howard...
17            sport  connors boost for british tennis former world ...
18         business  japanese banking battle at an end japan s sumi...
19             tech  games maker fights for survival one of britain...
20             tech  security warning over  fbi virus  the us feder...
21             tech  halo 2 heralds traffic explosion the growing p...
22            sport  bates seals takeover ken bates has completed h...
23            sport  cole faces lengthy injury lay-off aston villa ...
24             tech  mobile audio enters new dimension as mobile ph...
25            sport  moya fights back for indian title carlos moya ...
26    entertainment  career honour for actor dicaprio actor leonard...
27             tech  mobile gig aims to rock 3g forget about going ...
28         politics  terror suspects face house arrest uk citizens ...
29    entertainment  halloween writer debra hill dies screenwriter ...
...             ...                                                ...
2195          sport  owen delighted with real display michael owen ...
2196       business  gm issues 2005 profits warning general motors ...
2197       politics  campbell returns to election team ex-downing s...
2198       business  asian banks halt dollar s slide the dollar reg...
2199       business  wall street cool to ebay s profit shares in on...
2200           tech  uk pioneers digital film network the world s f...
2201       business  ban on forced retirement under 65 employers wi...
2202           tech  local net tv takes off in austria an austrian ...
2203       politics  profile: david miliband david miliband s rapid...
2204           tech  argonaut founder rebuilds empire jez san  the ...
2205  entertainment  dance music not dead says fatboy dj norman coo...
2206       politics  kennedy questions trust of blair lib dem leade...
2207           tech  california sets fines for spyware the makers o...
2208  entertainment  snicket tops us box office chart the film adap...
2209          sport  time to get tough on friendlies  for an intern...
2210       politics  teens  know little  of politics teenagers ques...
2211  entertainment  lopez misses uk charity premiere jennifer lope...
2212       business  christmas shoppers flock to tills shops all ov...
2213           tech  progress on new internet domains by early 2005...
2214       business  bush budget seeks deep cutbacks president bush...
2215            NaN  junk e-mails on relentless rise spam traffic i...
2216            NaN  top stars join us tsunami tv show brad pitt  r...
2217            NaN  rings of steel combat net attacks gambling is ...
2218            NaN  davies favours gloucester future wales hooker ...
2219            NaN  beijingers fume over parking fees choking traf...
2220            NaN  cars pull down us retail figures us retail sal...
2221            NaN  kilroy unveils immigration policy ex-chatshow ...
2222            NaN  rem announce new glasgow concert us band rem h...
2223            NaN  how political squabbles snowball it s become c...
2224            NaN  souness delight at euro progress boss graeme s...

[2225 rows x 2 columns]

In [2]:
# Data Overiview
df['category'].value_counts()

sport            509
business         508
politics         415
tech             399
entertainment    384
Name: category, dtype: int64

### Creating Train and Test Datasets

Note that the labels for test data will not be present in the dataset and hence they are mentioned as NaN.

In [3]:
# The last 10 rows in the csv file are query points, so loading them into test data.
# And loading the reamining points to train_data for which labels are given.

train_data = df.iloc[:-10,:]
test_data = df.iloc[-10:,:]

In [4]:
# For train_data here the labels are in the column named "category".
train_data

           category                                               text
0              tech  tv future in the hands of viewers with home th...
1          business  worldcom boss  left books alone  former worldc...
2             sport  tigers wary of farrell  gamble  leicester say ...
3             sport  yeading face newcastle in fa cup premiership s...
4     entertainment  ocean s twelve raids box office ocean s twelve...
5          politics  howard hits back at mongrel jibe michael howar...
6          politics  blair prepares to name poll date tony blair is...
7             sport  henman hopes ended in dubai third seed tim hen...
8             sport  wilkinson fit to face edinburgh england captai...
9     entertainment  last star wars  not for children  the sixth an...
10    entertainment  berlin cheers for anti-nazi film a german movi...
11         business  virgin blue shares plummet 20% shares in austr...
12         business  crude oil prices back above $50 cold weather a...
13         politics  hague  given up  his pm ambition former conser...
14            sport  moya emotional after davis cup win carlos moya...
15         business  s korean credit card firm rescued south korea ...
16         politics  howard backs stem cell research michael howard...
17            sport  connors boost for british tennis former world ...
18         business  japanese banking battle at an end japan s sumi...
19             tech  games maker fights for survival one of britain...
20             tech  security warning over  fbi virus  the us feder...
21             tech  halo 2 heralds traffic explosion the growing p...
22            sport  bates seals takeover ken bates has completed h...
23            sport  cole faces lengthy injury lay-off aston villa ...
24             tech  mobile audio enters new dimension as mobile ph...
25            sport  moya fights back for indian title carlos moya ...
26    entertainment  career honour for actor dicaprio actor leonard...
27             tech  mobile gig aims to rock 3g forget about going ...
28         politics  terror suspects face house arrest uk citizens ...
29    entertainment  halloween writer debra hill dies screenwriter ...
...             ...                                                ...
2185       business  us bank  loses  customer details the bank of a...
2186       business  battered dollar hits another low the dollar ha...
2187          sport  jones files conte lawsuit marion jones has fil...
2188          sport  mexicans tracking unhappy juninho mexican outf...
2189           tech  mobile networks seek turbo boost third-generat...
2190          sport  newry to fight cup exit in courts newry city a...
2191       business  iraqi voters turn to economic issues beyond th...
2192           tech  us duo in first spam conviction a brother and ...
2193       business  us consumer confidence up consumers  confidenc...
2194       business  india-pakistan peace boosts trade calmer relat...
2195          sport  owen delighted with real display michael owen ...
2196       business  gm issues 2005 profits warning general motors ...
2197       politics  campbell returns to election team ex-downing s...
2198       business  asian banks halt dollar s slide the dollar reg...
2199       business  wall street cool to ebay s profit shares in on...
2200           tech  uk pioneers digital film network the world s f...
2201       business  ban on forced retirement under 65 employers wi...
2202           tech  local net tv takes off in austria an austrian ...
2203       politics  profile: david miliband david miliband s rapid...
2204           tech  argonaut founder rebuilds empire jez san  the ...
2205  entertainment  dance music not dead says fatboy dj norman coo...
2206       politics  kennedy questions trust of blair lib dem leade...
2207           tech  california sets fines for spyware the makers o...
2208  entertainment  snicket tops us box office chart the film adap...
2209          sport  time to get tough on friendlies  for an intern...
2210       politics  teens  know little  of politics teenagers ques...
2211  entertainment  lopez misses uk charity premiere jennifer lope...
2212       business  christmas shoppers flock to tills shops all ov...
2213           tech  progress on new internet domains by early 2005...
2214       business  bush budget seeks deep cutbacks president bush...

[2215 rows x 2 columns]

In [5]:
test_data

     category                                               text
2215      NaN  junk e-mails on relentless rise spam traffic i...
2216      NaN  top stars join us tsunami tv show brad pitt  r...
2217      NaN  rings of steel combat net attacks gambling is ...
2218      NaN  davies favours gloucester future wales hooker ...
2219      NaN  beijingers fume over parking fees choking traf...
2220      NaN  cars pull down us retail figures us retail sal...
2221      NaN  kilroy unveils immigration policy ex-chatshow ...
2222      NaN  rem announce new glasgow concert us band rem h...
2223      NaN  how political squabbles snowball it s become c...
2224      NaN  souness delight at euro progress boss graeme s...

## Custom Implementation

### Instructions:

  1. Read in the train_data.
  2. Vectorize train_data using sklearns built in tfidf vectorizer.
  3. Ignore unigrams and make use of both **bigrams & trigrams** and also limit the **max features** to **4000** and **minimum document frequency** to **10**.
  4. After the tfidf vectors are generated as mentioned above, next task is to generate random hyperplanes.
  5. Generate **5 random hyperplanes**. And generate the hyperplanes using a random normal distribution with **mean zero and variance 1**. 
  6. We have set the **numpy random seed to zero**, please do not change it. And then you can make use of **np.random.normal** to generate the vectors for hyperplanes.
  7. As mentioned in the course videos, compute the hash function and also the corresponding hash table for it.
  8. Once the hash table is generated now take in each of the query points from the test data.
  9. Vectorize those query points using the same tfidf vectorizer as mentioned above.
  10. Now use the hash function on this query point and fetch all the similar data points from the hashtable.
  11. Use cosine similarity to compute **11-Nearest Neighbours** from the list of data points obtained in the above step.
  12. Take a majority vote among the 11-Nearest Neighbours and predict the class label for the query point in the test data.
  13. **In case of a tie** in the obtained labels from nearest neighbours, you can pick a label after sorting all the labels **alphabetically**(A-Z), i.e. for example labels starting with A would get more preference than labels starting with Z.
  14. Repeat steps 9 to 13 for all the points in the test data and then finally return a list with all the predicted labels.
  15. Note that there are a total of 10 data points in the test data so the final list you return should be of length 10.
  16. Also note that the cosine similarity function should be written from scratch, you should not directly make use of existing libraries.
  17. Please use the formula of cosine similarity as explained in the course videos, you can make use of numpy or scipy to calculate dot or norm or transpose.

In [17]:
#==========================================================================================
# Create function which predict the labels of test set usnig LSH +KNN
#==========================================================================================

import numpy as np
import pandas as pd
import os
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm
from numpy import dot
from numpy.linalg import norm
from collections import defaultdict

def predictLabels (test_data):
#============================================================================================================================
                                                #Train Data#
                                                #Hash Table#
#============================================================================================================================
    
    np.random.seed(1)
    max_features=4000 #max features for tf-idf
    ngram_min=2 #min n_gram allowed
    ngram_max=3 # max n_gram allowed
    min_df=10 #min_df value for tf-idf vectorizer
    k_neigh=11 #number of nearest neighbours to consider from the common bin
    num_hyper_planes=5 #number of random hyper planes to be generated
    vectorizer = TfidfVectorizer(ngram_range=(ngram_min,ngram_max),max_features=max_features,min_df=min_df)
    train_vectors= vectorizer.fit_transform(train_data.text).toarray()
    #generating random hyper planes
    random_hyper_planes=[]
    for i in range(num_hyper_planes):
        random_hyper_planes.append(np.random.normal(0,1,train_vectors.shape[1]))
    planes=np.array(random_hyper_planes).reshape(train_vectors.shape[1],num_hyper_planes)
    dist_train= np.dot(train_vectors,planes)
    hashed_train = list(map(tuple, (dist_train > 0).astype(int)))
    buckets = defaultdict(list)
    for i, row in enumerate(hashed_train):
        buckets[row].append(i)
    Hash_table=dict(buckets)
#============================================================================================================================
                                                #Test Data#
                                                #Hash Keys #
#============================================================================================================================
    test_vectors=vectorizer.transform(test_data.text).toarray()
    dist_test=np.dot(test_vectors,planes)
    hashed_test = list(map(tuple, (dist_test > 0).astype(int)))
    Neigherbor_index=[Hash_table.get(key) for key in hashed_test]
#==============================================#Top 11 Nearest data points for each test data points#===============================
    top_11=[]
    for i in range(0,len(Neigherbor_index)):
        consine_similarities=dict()
        for j in range(len(train_vectors[Neigherbor_index[i]])):
            cos_sim = dot(train_vectors[Neigherbor_index[i]][j],test_vectors[i])/(norm(train_vectors[Neigherbor_index[i]][j])*norm(test_vectors[i]))
            consine_similarities[Neigherbor_index[i][j]]=cos_sim
        top_11.append(consine_similarities)
    def keyfunction(k):
        return d[k]
    Pred_labels=[]
    for i in range(len(top_11)):
        d=top_11[i]
        top=[key for key in sorted(d, key=keyfunction, reverse=True)[:k_neigh]]
        label=list(train_data.iloc[top].category)
        Pred_labels.append(label)
    class_labels=sorted(list(set(train_data.category.values)))
    test_pred_counts=[]
    for i in range(len(Pred_labels)):
        exc=[]
        for j in class_labels:
            exc.append(Pred_labels[i].count(j))
        test_pred_counts.append(exc)
    test_pred_counts=np.array(test_pred_counts)
    max_vals=np.max(np.array(test_pred_counts),axis=1)
    class_label_predictions=[]
    for i in range(len(test_pred_counts)):
        for j in range(len(class_labels)):
            if test_pred_counts[i][j]==max_vals[i]:
                max_voted_class_label=class_labels[j]
                break
        class_label_predictions.append(max_voted_class_label)
    return class_label_predictions

## Grader Cell

Please execute the following Grader cell to verify the correctness of your above implementation. This cell will print "Success" if your implmentation of the predictLabels() is correct, else, it will print "Failed". Make sure you get a "Success" before you submit the code in the classroom.

In [19]:
###########################################
## GRADER CELL: Do NOT Change this.
# This cell will print "Success" if your implmentation of the predictLabels() is correct and the accuracy obtained is above 80%.
# Else, it will print "Failed"
###########################################
import numpy as np

# Predict the labels using the predictLabels() function
Y_custom = np.array(predictLabels(test_data))

# Reference grader array - DO NOT MODIFY IT
Y_grader = np.array(['tech', 'entertainment', 'tech', 'sport', 'business', 'business', 'politics', 'entertainment', 'politics', 'sport'])

# Calculating accuracy by comparing Y_grader and Y_custom
accuracy = np.sum(Y_grader==Y_custom) * 10

if accuracy >= 80:
    print("******** Success ********","Accuracy Achieved = ", accuracy,'%')
else:
    print("####### Failed #######","Accuracy Achieved = ", accuracy,'%')
    print("\nY_grader = \n\n", Y_grader)
    print("\n","*"*50)
    print("\nY_custom = \n\n", Y_custom)

******** Success ******** Accuracy Achieved =  80 %